<html>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=OFF",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:1",
	</GAME-STYLE>
-->
<body background=PNG/BG.PNG text=white link=white vlink=white bgcolor=black>

<basefont size=2>
<B>


<img src=PNG/LOGO1.PNG width=240 height=50><img src=PNG/LOGO2.PNG width=240 height=50><br>

<table width=480 cellspacing=2 border=0>
<tr>
<td width=480>

				<center>皓月遠程聯機平臺（皓月雲）<BR>堅持免費公益運營２０１３至今，如果喜歡請捐助我</center>
				
			<center>
	<table width=477 bgcolor=black border=1 bordercolor=#1C64FE cellspacing=0>
		<tr>
		<td valign=top WIDTH=159>
			<center>
			聯機QQ群<BR>
			<img ANIME=20 src="PNG/y_qqqun.png"  name=submit width=120 height=120 alt="" >
			</center>
			</td>
			<td valign=top WIDTH=159>
			<center>
			捐助用支付寶<BR>
			<img ANIME=20 src="PNG/y_alipay.png"  name=submit width=120 height=120 alt="" >
			</center>
			</td>
			<td valign=top WIDTH=159>
			<center>
			捐助用微信<BR>
			<img ANIME=20 src="PNG/y_WeChat.png"  name=submit width=120 height=120 alt="" >
			</center>
			</td>
		</tr>
	</table>
	
			</center>
	<a href="DL_TOP.PHP">按下［Ｏ］回首頁</a>
	</td>

</tr>
</table>


<img src=PNG/B_START.PNG width=17 height=17>:退出皓月云配信服務   


<!--adjust--><table cellspacing=0 height=4><tr><td></table>


<!--previously load other png-->
<br><br><br><br><br><br><br>
<img src=PNG/B_X.PNG>
<img src=PNG/B_REC.PNG>
<img src=PNG/B_TRI.PNG>
<img src=PNG/BOARD.PNG>
<img src=PNG/T_RED.PNG>
<img src=PNG/T_GRN.PNG>	
<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>

aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>

aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>

aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>

aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>

aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>

aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>
aaaaaaaaaa<B>bbbbbbbbbb</B>cccccccccc<B>dddddddddd</B>eeeeeeeeee<BR>ffffffffff<B>gggggggggg</B>hhhhhhhhhh<B>iiiiiiiiii</B>jjjjjjjjjj<BR>

</body>
</html>