<html>
<!--
	<GAME-STYLE>
		"MOUSE=OFF",
		"SCROLL=OFF",
		"TITLE=OFF",
		"BACK=ON:DL_TOP.PHP",
		"FORWARD=OFF",
		"CANCEL=OFF",
		"RELOAD=OFF",
		"CHOICE_MV=OFF",
		"LINK_U=OFF",
		"FRONT_LABEL=ON:6",
		"MOVE_CHAR=http://219.101.226.65/psp/MHP2G/GIF/ro-dos.gif,256,145,4,1,2,30,-82,100",
		"MOVE_CHAR=http://219.101.226.65/psp/MHP2G/GIF/conga.gif,169,69,5,1,2,86,272,050",
	</GAME-STYLE>
-->
<body text=white link=white vlink=white bgcolor=blue background=http://219.101.226.65/psp/MHP2G/GIF/BG.gif>
<basefont size=2>
<B>
<img src=http://219.101.226.65/psp/MHP2G/GIF/LOGO10.gif width=200 height=50 alt="Quest"><img src=http://219.101.226.65/psp/MHP2G/GIF/LOGO2.gif width=280 height=50 alt="MHP2nd"><br>
<table width=480 height=197 cellspacing=0 cellpadding=0 border=0>
<tr>
		<form action="DL_MENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src="http://219.101.226.65/psp/MHP2G/GIF/SELECT1.gif" name=submit width=190 height=160 alt="Event">
	</td>
		</form>
		<form action="DL_CMENU.PHP" method=get>
	<td width=240 height=196 align=center valign=center>
		 <input type=hidden name=pg_no value=0>
		 <input ANIME=1 type=image src="http://219.101.226.65/psp/MHP2G/GIF/SELECT2.gif" name=submit width=190 height=160 alt="Challenge">
	</td>
		</form>
</tr>
</table>
<table cellspacing=0 cellpadding=0><tr><td width=480 height=25 background=http://219.101.226.65/psp/MHP2G/GIF/BUTTON2.gif></td></tr></table>
</body>
</html>
